"""empty message

Revision ID: 11ce98c7a5e9
Revises: 78a44fac209e
Create Date: 2019-05-08 22:31:57.152120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ce98c7a5e9'
down_revision = '78a44fac209e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('baby_status', sa.Integer(), nullable=False))
    op.add_column('device', sa.Column('device_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'device_status')
    op.drop_column('device', 'baby_status')
    # ### end Alembic commands ###